### notes , change name and status due to testcase
POST {{host}}/notes
Content-Type: application/json


{
  "name": "abcdefg",
  "title":  "netflix",
  "status": "unsubscribe"
}

### notes randomly
POST {{host}}/notes
Content-Type: application/json


{
  "name": "{{$random.alphanumeric(8)}}",
  "title":  "netflix",
  "status": "subscribe"
}
