### findAll
GET http://localhost:8080/subscribers
Content-Type: application/json

### findAllByName
GET http://localhost:8080/subscribers?name={{$random.alphanumeric(8)}}
Content-Type: application/json

### findAllByTitile
GET http://localhost:8080/subscribers?title={{$random.alphanumeric(8)}}
Content-Type: application/json

### save
POST http://localhost:8080/subscribers
Content-Type: application/json
X-Request-ID: {{$random.alphanumeric(25)}}

{
  "name":  "{{$random.alphanumeric(8)}}",
  "title": "netflix",
  "description":  "",
  "status": "subscribe"
}

### update for note
PUT http://localhost:8080/subscribers/4
Content-Type: application/json
X-Request-ID: {{$random.alphanumeric(25)}}

{
  "name":  "abcdefg",
  "title": "netflix",
  "description":  "",
  "status": "unsubscribe"
}

### save for note
POST http://localhost:8080/subscribers
Content-Type: application/json
X-Request-ID: {{$random.alphanumeric(25)}}

{
  "name":  "abcdefg",
  "title": "netflix",
  "description":  "",
  "status": "subscribe"
}

