### findAll
GET {{host}}/configs
Content-Type: application/json

### save random
POST {{host}}/configs
Content-Type: application/json


{
  "configKey":  "{{$random.alphanumeric(8)}}",
  "configValue": "{{$random.alphanumeric(8)}}"
}

### save
POST {{host}}/configs
Content-Type: application/json


{
  "configKey":  "netflix.price",
  "configValue": "419"
}

### update
PUT {{host}}/configs
Content-Type: application/json


{
  "configKey":  "netflix.price",
  "configValue": "399"
}

### GET key
GET {{host}}/configs/netflix.price
