### findAll
GET http://localhost:8080/api/subscribers
Content-Type: application/json

### findAllByName
GET http://localhost:8080/api/subscribers?name={{$random.alphanumeric(8)}}
Content-Type: application/json

### findAllByTitile
GET http://localhost:8080/api/subscribers?title={{$random.alphanumeric(8)}}
Content-Type: application/json

